name: "Lint and Test Code"

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - widget-hmi  # build-image runs lint and tests for the release branch
  pull_request:

jobs:
  lint:
    name: Lint Code
    uses: ./.github/workflows/run-linting.yml
    secrets: inherit

  test:
    name: Test Code
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
#    needs: lint
